# Generated by Django 5.2 on 2025-05-22 07:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Команда с таким названием уже существует'}, max_length=100, unique=True, verbose_name='Название команды')),
                ('avatar', models.ImageField(blank=True, default='team_avatars/default.jpg', null=True, upload_to='team_avatars/', verbose_name='Аватар команды')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('invite_code', models.CharField(max_length=32, unique=True, verbose_name='Код приглашения')),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captained_teams', to=settings.AUTH_USER_MODEL, verbose_name='Капитан')),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название турнира')),
                ('max_teams', models.IntegerField(choices=[(4, '4'), (8, '8'), (16, '16'), (32, '32'), (64, '64'), (128, '128'), (256, '256'), (512, '512')], verbose_name='Максимальное количество команд')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('discipline', models.CharField(choices=[('Dota 2', 'Dota 2'), ('CS 2', 'CS 2'), ('Valorant', 'Valorant'), ('LoL', 'League of Legends')], max_length=50, verbose_name='Дисциплина')),
                ('game_format', models.CharField(choices=[('1x1', '1x1'), ('2x2', '2x2'), ('3x3', '3x3'), ('5x5', '5x5')], max_length=50, verbose_name='Формат игры')),
                ('tournament_format', models.CharField(choices=[('BO1', 'BO1'), ('BO3', 'BO3'), ('BO5', 'BO5')], max_length=50, verbose_name='Формат турнира')),
                ('location', models.CharField(choices=[('China', 'Китай'), ('Western Europe', 'Западная Европа'), ('Eastern Europe', 'Восточная Европа'), ('Southeast Asia', 'ЮВ Азия'), ('North America', 'Северная Америка'), ('South America', 'Южная Америка')], max_length=50, verbose_name='Локация')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('players', models.ManyToManyField(related_name='tournament_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Игроки, участвующие в турнире')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tournament')),
            ],
            options={
                'verbose_name': 'Регистрация на турнир',
                'verbose_name_plural': 'Регистрации на турниры',
                'unique_together': {('tournament', 'team')},
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='registered_teams',
            field=models.ManyToManyField(blank=True, related_name='tournaments', through='app.TournamentRegistration', to='app.team', verbose_name='Зарегистрированные команды'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, default='avatars/default.jpg', null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='app.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
