# Generated by Django 5.2 on 2025-06-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bracketstage_remove_tournament_tournament_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_format',
            field=models.CharField(choices=[('single_elimination', 'Single Elimination'), ('double_elimination', 'Double Elimination'), ('round_robin', 'Round Robin')], default='single_elimination', max_length=50, verbose_name='Формат турнира'),
        ),
    ]
