# Generated by Django 5.2 on 2025-06-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tournament_tournament_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_format',
            field=models.CharField(blank=True, choices=[('single_elimination', 'Single Elimination'), ('double_elimination', 'Double Elimination'), ('round_robin', 'Round Robin')], max_length=50, null=True, verbose_name='Формат турнира'),
        ),
    ]
