# Generated by Django 5.2 on 2025-06-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_bracketmatch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundrobinresult',
            name='map_difference',
            field=models.IntegerField(default=0, verbose_name='Разница карт'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_teams',
            field=models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], verbose_name='Максимальное количество команд'),
        ),
    ]
