# Generated by Django 5.2 on 2025-06-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_tournament_max_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=models.ImageField(blank=True, default='team_avatars/default_team.jpg', null=True, upload_to='team_avatars/', verbose_name='Аватар команды'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(error_messages={'unique': 'Команда с таким названием уже существует'}, max_length=20, unique=True, verbose_name='Название команды'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название турнира'),
        ),
    ]
