# Generated by Django 5.2 on 2025-06-15 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_team_avatar_alter_team_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bracketmatch',
            options={'ordering': ['order'], 'verbose_name': 'Матч турнирной сетки', 'verbose_name_plural': 'Матчи турнирной сетки'},
        ),
        migrations.AlterModelOptions(
            name='roundrobinresult',
            options={'ordering': ['-points', '-wins', '-draws', 'losses'], 'verbose_name': 'Результат команды в Round Robin', 'verbose_name_plural': 'Результаты команд в Round Robin'},
        ),
        migrations.AlterUniqueTogether(
            name='roundrobinmatch',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='roundrobinresult',
            name='draws',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bracketmatch',
            name='is_bye',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bracketmatch',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bracketmatch',
            name='team1_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bracketmatch',
            name='team2_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roundrobinmatch',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_round_robin_matches', to='app.team'),
        ),
        migrations.AlterField(
            model_name='roundrobinmatch',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_round_robin_matches', to='app.team'),
        ),
        migrations.RemoveField(
            model_name='roundrobinmatch',
            name='format',
        ),
        migrations.RemoveField(
            model_name='roundrobinmatch',
            name='winner',
        ),
    ]
