# Generated by Django 5.2 on 2025-06-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_bracketmatch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundrobinmatch',
            name='format',
            field=models.CharField(choices=[('BO1', 'Best of 1'), ('BO3', 'Best of 3'), ('BO5', 'Best of 5')], default='BO1', max_length=3, verbose_name='Формат матча'),
        ),
    ]
